### ISSUE TITLE
what is it connecting to ?

### ISSUE THREAD

**Issue by tieandsuit** [nirbhayph/Logistics-Management-System#1]
not sure why is this trying to connect to Amazon server . 	

$db = "(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = nirbhaylms.c3x2dwubess3.us-west-2.rds.amazonaws.com)(PORT = 1521)))(CONNECT_DATA=(SID=orcl)))";

**Comment by nirbhayph** [comment]
You can connect it to your own rds if you're using Amazon. Otherwise however you want to connect to your db. (Not maintaining this repo anymore)

**Comment by Kostas-lab** [comment]
Is there somewhere copy of db?  Will save some time :)
